# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-03-23 09:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('django_state_machine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='state',
            field=models.CharField(default='0', max_length=100, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
